[package]
name = "api"
version = "0.0.0"
edition = "2021"

[dependencies]
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
chrono = { workspace = true }
reqwest = { workspace = true }
sqlx = { workspace = true }
config = { path = "../config" }
auth = { path = "../auth" }
db = { path = "../db" }
notifications = { path = "../notifications" }
axum = { version = "0.6.18", features = [ "headers", "ws" ] }
hyper = "0.14.25"
tower = "0.4.13"
tower-http = { version = "0.3", features = [ "trace", "cors" ] }
futures = "0.3"
futures-util = { version = "0.3", default-features = false, features = [ "sink", "std" ] }
