services:
  db:
    image: postgres:15.5
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: tasks
    volumes:
      - db:/var/lib/postgresql/data
      - ./backend/db/migrations:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432

  backend:
    profiles:
      - staging
    depends_on:
      - db
    build: ./backend
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env

  frontend:
    profiles:
      - staging
    depends_on:
      - backend
    build: ./frontend
    ports:
      - 3000:3000

volumes:
  db:
