services:
    db:
        image: postgres:15.3
        restart: always
        ports:
            - 5433:5432
        volumes:
            - ./DATA:/var/lib/postgresql/data/
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres

    backend:
        depends_on:
            - db
        image: veetik/tasks-backend:prod
        restart: always
        env_file:
            - .env.prod
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.tasks-backend.entrypoints=https"
            - "traefik.http.routers.tasks-backend.tls=true"
            - "traefik.http.routers.tasks-backend.service=tasks-backend"
            - "traefik.http.routers.tasks-backend.rule=Host(`tasks-api.veetik.com`)"
            - "traefik.http.services.tasks-backend.loadbalancer.server.port=8000"
            - "traefik.docker.network=proxy"
        networks:
            - proxy
            - default

networks:
    proxy:
        external: true
