[package]
name = "backend"
version.workspace = true
edition.workspace = true

[dependencies]
tokio = { workspace = true }
tracing-subscriber = { workspace = true }
api = { path = "../api" }
notifications = { path = "../notifications" }