name: frontend checks

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'

env:
  FRONT_DIR: ./frontend

jobs:
  check_frontend:
    runs-on: macos-14

    defaults:
      run:
        working-directory: ${{ env.FRONT_DIR }}

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: install pnpm
        with:
          version: 9
          run_install: false

      - name: install node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: '${{ env.FRONT_DIR }}/pnpm-lock.yaml'

      - name: install deps
        run: pnpm install

      - name: check formatting
        run: pnpm run formatcheck

      - name: typecheck
        run: pnpm run typecheck

      - name: lint
        run: pnpm run lint

      - name: build
        run: pnpm run build
